spine/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'skin.views.index', name='index'),
    url(r'^lists/$', 'skin.views.lists', name='lists'),
    url(r'^list/', include([
        url(r'^create/$', 'skin.views.create_list', name='create'),
        url(r'^(?P<list_id>\d+)/', include([
            url(r'^$', 'skin.views.list', name='index'),
            url(r'^play/$', 'skin.views.list_play', name='play'),
            url(r'^beadj/$', 'skin.views.list_be_a_dj', name='be_a_dj'),
            url(r'^addamusic/$', 'skin.views.list_add_a_music', name='add_a_music'),
            url(r'^rmamusic/(?P<music_in_list_id>\d+)/$', 'skin.views.list_rm_a_music', name='rm_a_music'),
            url(r'^addayoutubemusic/(?P<yt_id>[-\w]+)/$', 'skin.views.list_add_a_yt_music', name='add_a_yt_music'),
        ], namespace='details')),
        url(r'^playpause/$', 'skin.views.list_music_playpause', name='music_playpause'),
        url(r'^skipmyturn/$', 'skin.views.list_skipmyturn', name='skipmyturn'),
        url(r'^forceplay/$', 'skin.views.list_force_play', name='force_play'),
    ], namespace='list')),
    url(r'^playerapi/(?P<list_id>\d+)/', include([
        url(r'^$', 'skin.views.player_api', name='index'),
        url(r'^started/$', 'skin.views.player_started', name='started'),
        url(r'^play/$', 'skin.views.player_play', name='play'),
        url(r'^pause/$', 'skin.views.player_pause', name='pause'),
        url(r'^ended/$', 'skin.views.player_ended', name='ended'),
        url(r'^updateseconds/$', 'skin.views.player_update_seconds', name='update_seconds'),
    ], namespace='player_api')),
    url(r'^changedjinfo/$', 'skin.views.change_dj', name='change_dj'),

    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skin/forms.py
from brain.models import List, DJ
from django import forms


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['title', 'public']

class SearchYT(forms.Form):
    query = forms.CharField(label='')

class ChangeDJ(forms.ModelForm):
    class Meta:
        model = DJ
        fields = ['name']

skin/views.py
import json
from django.utils.translation import ugettext_lazy as _
from brain.sources.youtube import YoutubeMusic
from django.contrib import messages
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseForbidden
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
import requests
from brain.models import List, DJList, MusicInList
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from skin.forms import ListForm, SearchYT, ChangeDJ


def index(request):
    return redirect(reverse('lists'))

def lists(request):
    return render(request, 'lists/all.html')

@login_required
def create_list(request):
    form = ListForm(request.POST or None)
    if form.is_valid():
        list = form.save(commit=False)
        list.user = request.user
        list.save()
        return redirect(reverse('lists'))
    return render(request, 'lists/create.html', {
        'form': form
    })

def list(request, list_id):
    list = get_object_or_404(List, id=list_id)
    return render(request, 'lists/index.html', {
        'list': list
    })

@login_required
def list_play(request, list_id):
    list = get_object_or_404(List, id=list_id, user=request.user)
    return render(request, 'lists/play.html', {
        'list': list
    })

def list_be_a_dj(request, list_id):
    list = get_object_or_404(List, id=list_id)
    if not list in request.dj.lists.all():
        DJList.objects.create(
            dj=request.dj,
            list=list
        )
    return redirect(reverse('list:details:index', kwargs={'list_id': list.id}))

def list_add_a_music(request, list_id):
    list = get_object_or_404(List, id=list_id)

    form = SearchYT(request.POST or None)

    yt_results = []

    if form.is_valid():
        from urllib import quote
        q = quote(form.cleaned_data.get('query').encode('utf8'))
        r = requests.get('https://www.googleapis.com/youtube/v3/search?part=snippet&q={}&type=video&maxResults=20&key={}'.format(
            q,
            settings.YOUTUBE_API_KEY
        ))
        json_loaded = json.loads(r.text)
        yt_results = json_loaded.get('items')

    return render(request, 'lists/add_a_music.html', {
        'list': list,
        'form': form,
        'yt_results': yt_results
    })

def list_add_a_yt_music(request, list_id, yt_id):
    list = get_object_or_404(List, id=list_id)
    if list in request.dj.lists.all():
        try:
            ytmusic = YoutubeMusic.objects.get(yt_id=yt_id)
        except:
            youtube_url = 'https://www.youtube.com/watch?v={}'.format(yt_id)
            ytmusic, created = YoutubeMusic.objects.get_or_create(
                url=youtube_url
            )
        try:
            djlist = DJList.objects.get(
                dj=request.dj,
                list=list
            )
            MusicInList.objects.create(
                djlist=djlist,
                music=ytmusic,
            )
        except Exception, e:
            print e.message
    return redirect(reverse('list:details:index', kwargs={'list_id': list.id}))

def list_rm_a_music(request, list_id, music_in_list_id):
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__dj=request.dj)
    musicinlist.delete()
    return redirect(reverse('list:details:index', kwargs={'list_id': musicinlist.djlist.list.id}))

@csrf_exempt
def list_music_playpause(request):
    list_id = request.POST.get('list_id')
    list = get_object_or_404(List, id=list_id)
    if not list.now:
        return HttpResponseNotFound()
    if not list.now.djlist.dj == request.dj and not list.user == request.user:
        return HttpResponseForbidden()
    list.playpause()
    return JsonResponse({})

@csrf_exempt
def list_skipmyturn(request):
    list_id = request.POST.get('list_id')
    list = get_object_or_404(List, id=list_id)
    if not list.now:
        return HttpResponseNotFound()
    if not list.now.djlist.dj == request.dj and not list.user == request.user:
        return HttpResponseForbidden()
    list.playnext()
    return JsonResponse({})

@csrf_exempt
def list_force_play(request):
    music_in_list_id = request.POST.get('music_in_list_id')
    music_in_list = get_object_or_404(MusicInList, id=music_in_list_id)
    if not music_in_list.djlist.list.user == request.user:
        return HttpResponseForbidden()
    music_in_list.top()
    music_in_list.djlist.list.playnext()
    return JsonResponse({})

@login_required
def player_api(request, list_id):
    list = get_object_or_404(List, id=list_id, user=request.user)
    return JsonResponse({
        'now': list.now.serializer() if list.now else False
    })

@login_required
@csrf_exempt
def player_started(request, list_id):
    music_in_list_id = request.POST.get('music_in_list_id')
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__list__user=request.user)
    musicinlist.started = timezone.now()
    musicinlist.save(update_fields=['started'])
    return JsonResponse({})

@login_required
@csrf_exempt
def player_play(request, list_id):
    music_in_list_id = request.POST.get('music_in_list_id')
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__list__user=request.user)
    musicinlist.playing = True
    musicinlist.save(update_fields=['playing'])
    return JsonResponse({})

@login_required
@csrf_exempt
def player_pause(request, list_id):
    music_in_list_id = request.POST.get('music_in_list_id')
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__list__user=request.user)
    musicinlist.playing = False
    musicinlist.save(update_fields=['playing'])
    return JsonResponse({})

@login_required
@csrf_exempt
def player_ended(request, list_id):
    music_in_list_id = request.POST.get('music_in_list_id')
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__list__user=request.user)
    musicinlist.delete()
    return JsonResponse({})

@login_required
@csrf_exempt
def player_update_seconds(request, list_id):
    music_in_list_id = request.POST.get('music_in_list_id')
    musicinlist = get_object_or_404(MusicInList, id=music_in_list_id, djlist__list__id=list_id, djlist__list__user=request.user)
    musicinlist.seconds = int(request.POST.get('seconds'))
    musicinlist.save(update_fields=['seconds'])
    return JsonResponse({})

def change_dj(request):
    form = ChangeDJ(request.POST or None, instance=request.dj)
    if form.is_valid():
        messages.success(request, _(u'Your dj name was changed successfully!!'))
        form.save()
    return render(request, 'change_dj.html', {
        'form': form
    })

skin/templates/lists/add_a_music.html
{% extends 'base.html' %}

{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="col-xs-12">
        <h2><a href="{% url 'list:details:index' list_id=list.id %}">{{ list.title }}</a></h2>
        <h4>{% trans 'Search music on Youtube' %}:</h4>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-block btn-primary">{% trans 'Search' %}</button>
            {% endbuttons %}
        </form>
        {% if yt_results %}
            {% for result in yt_results %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-3 col-md-4">
                                <img class="img-responsive" src="{{ result.snippet.thumbnails.high.url }}">
                            </div>
                            <div class="col-lg-9 col-md-8">
                                <h4>{{ result.snippet.title }}</h4>
                                <p>{{ result.snippet.description }}</p>
                                <p><a href="https://www.youtube.com/watch?v={{ result.id.videoId }}" target="_blank" class="btn btn-primary">{% trans 'Preview' %}</a> <a href="{% url 'list:details:add_a_yt_music' list_id=list.id yt_id=result.id.videoId %}" class="btn btn-lg btn-warning">{% trans 'Add Music' %}</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

skin/templates/lists/all.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <div class="col-xs-12">
        <h1>{% trans 'Lists' %}</h1>
        <hr>
    </div>
    {% for list in dj.lists_available %}
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'list:details:index' list_id=list.id %}" class="no-text-decoration">
                <div class="panel {% if list in dj.lists.all %}panel-success{% else %}panel-default{% endif %}">
                    <div class="panel-body">
                        <h4>{{ list.title }}</h4>
                        <p>{% trans 'owner' %}: {{ list.user.first_name }}</p>
                    </div>
                    <div class="panel-heading">
                        <div class="text-center">{% if list.public %}{% trans 'Public' %}{% else %}{% trans 'Private' %}{% endif %}</div>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

skin/templates/lists/create.html
{% extends 'base.html' %}

{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-12">
                <h1>{% trans 'Create Music List' %}</h1>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">{% trans 'Create' %}</button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

skin/templates/lists/index.html
{% extends 'base.html' %}

{% load i18n %}
{% load brain_extras %}
{% load humanize %}

{% block content %}
    {% get_dj_list dj list as djlist %}
    <div class="col-md-12">
        <h1>{{ list.title }}</h1>
        {% if not list in dj.lists.all %}
            <div class="alert alert-warning">
                <h4>{% trans 'You do not participate in this party as a DJ!' %}</h4>
                <p><a href="{% url 'list:details:be_a_dj' list_id=list.id %}" class="btn btn-primary">Be a DJ</a></p>
            </div>
        {% else %}
            <h4>{% trans "You're the #" %}{{ djlist.str_order }}</h4>
            <p>
                <a href="{% url 'list:details:add_a_music' list_id=list.id %}" class="btn btn-lg btn-warning">{% trans 'Add a Music' %}</a>
                {% if user.is_authenticated and list.user == user %}<a href="{% url 'list:details:play' list_id=list.id %}" target="_blank" class="btn btn-danger">{% trans 'Play' %}</a>{% endif %}
            </p>
            <hr>
            {% if list.now %}
                <h3 class="text-center">{% trans 'Playing now' %}</h3>
                {% upcoming_render_with_request list.now %}
            {% endif %}
            <h3 class="text-center">{% trans 'Upcoming Music' %}</h3>
            {% for musicinlist in list.upcoming %}
                <div class="row">
                    <div class="col-md-2">
                        <p class="text-right"><strong>{{ musicinlist.added|naturaltime }}</strong><br>DJ {{ musicinlist.djlist.dj.name }} {% trans 'put on the set' %}</p>
                        {% if musicinlist.djlist.dj == dj %}<p class="text-right"><a href="{% url 'list:details:rm_a_music' list_id=list.id music_in_list_id=musicinlist.id %}" class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-remove"></span> {% trans 'Remove' %}</a></p>{% endif %}
                        {% if musicinlist.djlist.list.user == user %}<p class="text-right"><button onclick="play({{ musicinlist.id }})" class="btn btn-info"><span class="glyphicon glyphicon-play"></span> Play</button></p>{% endif %}
                    </div>
                    <div class="col-md-10">
                        {{ musicinlist.upcoming_render }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

{% block extra-js %}
    <script type="text/javascript">
        reload = true;
    </script>
{% endblock %}

skin/templates/lists/play.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PlayThisMusic - PLAY</title>

    <link href="{% static 'vendor/bower_components/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="full-screen">
<div id="player"></div>

<script src="{% static 'vendor/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/swfobject/swfobject.js' %}"></script>
<script type="text/javascript">
    var $player, now, onYouTubePlayerReady, ytplayer;

    function seconds_update(now_id){
        var seconds;
        if(now && now.id == now_id){
            switch (now.music.type) {
                case 'youtubemusic':
                    var
                            $video = $player.find('.video'),
                            video = $video[0];

                    seconds = parseInt(video.currentTime);
                    break;
                case 'youtubeclassic':
                    seconds = parseInt(ytplayer.getCurrentTime());
                    break;
            }
            $.ajax({
                type: 'POST',
                url: '{% url 'player_api:update_seconds' list_id=list.id %}',
                data: {
                    music_in_list_id: now.id,
                    seconds: seconds
                },
                success: function (data){
                    setTimeout(function () {
                        seconds_update(now.id);
                    }, 750);
                }
            });
        }
    }

    function play(){
        switch (now.music.type){
            case 'youtubemusic':
                var
                        $video = $player.find('.video'),
                        video = $video[0];
                video.play();
                break;
            case 'youtubeclassic':
                ytplayer.playVideo();
                break;
        }
        $.ajax({
            type: 'POST',
            url: '{% url 'player_api:play' list_id=list.id %}',
            data: {
                music_in_list_id: now.id
            },
            success: function (data){}
        });
    }
    function pause(){
        switch (now.music.type){
            case 'youtubemusic':
                var
                        $video = $player.find('.video'),
                        video = $video[0];
                video.pause();
                break;
            case 'youtubeclassic':
                ytplayer.pauseVideo();
                break;
        }
        $.ajax({
            type: 'POST',
            url: '{% url 'player_api:pause' list_id=list.id %}',
            data: {
                music_in_list_id: now.id
            },
            success: function (data){}
        });
    }

    function ended(){
        $.ajax({
            type: 'POST',
            url: '{% url 'player_api:ended' list_id=list.id %}',
            data: {
                music_in_list_id: now.id
            },
            success: function (data){
                playing_now();
            }
        });
    }

    function playing_now(){
        $.ajax({
            type: 'GET',
            url: '{% url 'player_api:index' list_id=list.id %}',
            success: function (data){
                if(data.now){
                    now = data.now;
                    $player.html(data.now.music.player_render);
                    switch (now.music.type){
                        case 'youtubemusic':
                            var
                                    $video = $player.find('.video'),
                                    video = $video[0];

                            $.ajax({
                                type: 'POST',
                                url: '{% url 'player_api:started' list_id=list.id %}',
                                data: {
                                    music_in_list_id: now.id
                                },
                                success: function (data){
                                    play();
                                    seconds_update(now.id);
                                }
                            });

                            video.addEventListener('ended', function (){
                                ended();
                            }, false);
                            break;
                        case 'youtubeclassic':
                            var params = { allowScriptAccess: 'always', scale: 'exactFit' };
                            var atts = { id: 'ytplayer' };
                            swfobject.embedSWF('http://www.youtube.com/v/'+now.music.extra.yt_id+'?enablejsapi=1&playerapiid=ytplayer&version=3', 'ytapiplayer', '100%', '100%', '8', null, null, params, atts);

                            onYouTubePlayerReady = function(playerId){
                                ytplayer = document.getElementById('ytplayer');

                                ytplayer.addEventListener('onStateChange', 'YTClassicOnStateChange');

                                $.ajax({
                                    type: 'POST',
                                    url: '{% url 'player_api:started' list_id=list.id %}',
                                    data: {
                                        music_in_list_id: now.id
                                    },
                                    success: function (data){
                                        ytplayer.seekTo(now.seconds, true);
                                        play();
                                        seconds_update(now.id);
                                    }
                                });
                            };
                            break;
                    }
                } else {
                    $player.html('<h1 class="text-center">{% trans 'without music :(' %}</h1>');
                }
            }
        });
    }

    function YTClassicOnStateChange(e){
        if(e == 0){
            ended();
        }
    }

    $(document).ready(function (){
        var
                player_ws_url = 'ws://'+window.location.hostname+':'+window.location.port+'/ws/listplayer-{{ list.id }}?subscribe-broadcast',
                player_ws = new WebSocket(player_ws_url);

        $player = $('#player');

        player_ws.onmessage = function(e) {
            var data = JSON.parse(e.data);
            switch(data.act){
                case 'playpause':
                    if(data.playing){
                        pause();
                    } else {
                        play();
                    }
                    break;
                case 'playnext':
                    ended();
                    break;
                default:
                    console.log(data);
                    break;
            }
        };
        playing_now();
    });
</script>
</body>
</html>